# Generated by Django 5.0.6 on 2026-04-12 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0002_asset_cia_ratings"),
        ("privacy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataflow",
            name="data_subject_categories",
            field=models.TextField(
                blank=True,
                help_text="Categories of individuals whose data is processed",
                verbose_name="Data Subject Categories",
            ),
        ),
        migrations.AddField(
            model_name="dataflow",
            name="legal_basis",
            field=models.CharField(
                blank=True,
                help_text="e.g. Consent, Contract, Legal Obligation, Legitimate Interests",
                max_length=100,
                verbose_name="Legal Basis (GDPR Art. 6)",
            ),
        ),
        migrations.AddField(
            model_name="dataflow",
            name="lifecycle_stage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("collection", "Collection"),
                    ("processing", "Processing"),
                    ("storage", "Storage"),
                    ("sharing", "Sharing"),
                    ("archival", "Archival"),
                    ("deletion", "Deletion"),
                ],
                db_index=True,
                max_length=20,
                verbose_name="Lifecycle Stage",
            ),
        ),
        migrations.AddField(
            model_name="dataflow",
            name="personal_data_categories",
            field=models.TextField(
                blank=True,
                help_text="Types of personal data in this flow",
                verbose_name="Personal Data Categories",
            ),
        ),
        migrations.AddField(
            model_name="dataflow",
            name="processing_activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="data_flows",
                to="privacy.processingactivity",
                verbose_name="RoPA Processing Activity",
            ),
        ),
        migrations.AddField(
            model_name="dataflow",
            name="retention_period_days",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Retention Period (days)"
            ),
        ),
        migrations.AddField(
            model_name="dataflow",
            name="special_category_data",
            field=models.BooleanField(
                default=False, verbose_name="Contains Special Category Data (Art. 9)"
            ),
        ),
        migrations.AddField(
            model_name="dataflow",
            name="transfer_safeguards",
            field=models.TextField(
                blank=True,
                help_text="Standard Contractual Clauses, Adequacy Decision, BCR, etc.",
                verbose_name="Transfer Safeguards",
            ),
        ),
    ]
