# Generated by Django 5.0.6 on 2026-04-14 22:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0003_dataflow_gdpr_fields"),
        ("privacy", "0001_initial"),
        ("risks", "0003_risk_threats_vulnerabilities"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataLifecycleStage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("collection", "Collection"),
                            ("processing", "Processing"),
                            ("storage", "Storage"),
                            ("sharing", "Sharing"),
                            ("archival", "Archival"),
                            ("deletion", "Deletion"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Lifecycle Stage",
                    ),
                ),
                (
                    "purpose",
                    models.TextField(blank=True, verbose_name="Processing Purpose"),
                ),
                (
                    "legal_basis_gdpr",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        verbose_name="Legal Basis (GDPR Art. 6)",
                    ),
                ),
                (
                    "legal_basis_dpdpa",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        verbose_name="Legal Basis (DPDPA S.6/S.7)",
                    ),
                ),
                (
                    "data_subject_categories",
                    models.TextField(
                        blank=True, verbose_name="Data Subject Categories"
                    ),
                ),
                (
                    "personal_data_categories",
                    models.TextField(
                        blank=True, verbose_name="Personal Data Categories"
                    ),
                ),
                (
                    "special_category_data",
                    models.BooleanField(
                        default=False,
                        verbose_name="Special Category Data (Art. 9 / S.9)",
                    ),
                ),
                (
                    "retention_period_days",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Retention Period (days)"
                    ),
                ),
                (
                    "retention_justification",
                    models.TextField(
                        blank=True, verbose_name="Retention Justification"
                    ),
                ),
                (
                    "security_measures",
                    models.TextField(blank=True, verbose_name="Security Measures"),
                ),
                (
                    "third_party_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Third Party / Recipient",
                    ),
                ),
                (
                    "third_party_agreement",
                    models.BooleanField(
                        default=False, verbose_name="Third-Party Agreement in Place"
                    ),
                ),
                (
                    "transfer_safeguards",
                    models.TextField(blank=True, verbose_name="Transfer Safeguards"),
                ),
                (
                    "is_cross_border",
                    models.BooleanField(
                        default=False, verbose_name="Cross-Border Transfer"
                    ),
                ),
                (
                    "deletion_method",
                    models.TextField(
                        blank=True, verbose_name="Deletion / Disposal Method"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Stage Notes")),
                (
                    "compliance_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("met", "Met"),
                            ("partial", "Partially Met"),
                            ("not_met", "Not Met"),
                            ("na", "Not Applicable"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                        verbose_name="Overall Compliance Status",
                    ),
                ),
                (
                    "compliance_notes",
                    models.TextField(blank=True, verbose_name="Compliance Notes"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "data_flow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lifecycle_stages",
                        to="assets.dataflow",
                        verbose_name="Data Flow",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_lifecycle_stages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Stage Owner",
                    ),
                ),
                (
                    "processing_activity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lifecycle_stages",
                        to="privacy.processingactivity",
                        verbose_name="RoPA Processing Activity",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Lifecycle Stage",
                "verbose_name_plural": "Data Lifecycle Stages",
                "ordering": ["stage"],
                "unique_together": {("data_flow", "stage")},
            },
        ),
        migrations.CreateModel(
            name="DataLifecycleRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "framework",
                    models.CharField(
                        choices=[("gdpr", "GDPR"), ("dpdpa", "DPDPA (India)")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("requirement_key", models.CharField(max_length=100)),
                ("requirement_label", models.CharField(max_length=255)),
                ("article_reference", models.CharField(blank=True, max_length=60)),
                (
                    "rating",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("met", "Met"),
                            ("partial", "Partially Met"),
                            ("not_met", "Not Met"),
                            ("na", "Not Applicable"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "privacy_risk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lifecycle_requirements",
                        to="risks.risk",
                        verbose_name="Auto-Created Privacy Risk",
                    ),
                ),
                (
                    "stage_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirements",
                        to="assets.datalifecyclestage",
                        verbose_name="Stage Record",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lifecycle Compliance Requirement",
                "verbose_name_plural": "Lifecycle Compliance Requirements",
                "ordering": ["framework", "requirement_key"],
                "unique_together": {("stage_record", "requirement_key")},
            },
        ),
    ]
