# Generated by Django 5.0.6 on 2026-04-15 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0004_lifecycle_stages"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="datalifecyclerequirement",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_approval", "Pending Approval"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
                verbose_name="Approval Status",
            ),
        ),
        migrations.AddField(
            model_name="datalifecyclerequirement",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Approved At"
            ),
        ),
        migrations.AddField(
            model_name="datalifecyclerequirement",
            name="checker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="checked_requirements",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Reviewed By",
            ),
        ),
        migrations.AddField(
            model_name="datalifecyclerequirement",
            name="checker_notes",
            field=models.TextField(blank=True, verbose_name="Checker Notes"),
        ),
        migrations.AddField(
            model_name="datalifecyclerequirement",
            name="maker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="made_requirements",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Submitted By",
            ),
        ),
        migrations.AddField(
            model_name="datalifecyclerequirement",
            name="submitted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Submitted At"
            ),
        ),
        migrations.CreateModel(
            name="RequirementAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("rated", "Rated"),
                            ("submitted", "Submitted for Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "from_rating",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Previous Rating"
                    ),
                ),
                (
                    "to_rating",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="New Rating"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes / Reason")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="assets.datalifecyclerequirement",
                        verbose_name="Requirement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requirement_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Requirement Audit Log",
                "verbose_name_plural": "Requirement Audit Logs",
                "ordering": ["-timestamp"],
            },
        ),
    ]
