# Generated by Django 5.0.6 on 2026-03-18 15:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ThirdParty",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "vendor_type",
                    models.CharField(
                        choices=[
                            ("supplier", "Supplier"),
                            ("partner", "Partner"),
                            ("contractor", "Contractor"),
                            ("cloud_provider", "Cloud Provider"),
                            ("subprocessor", "Sub-Processor"),
                            ("other", "Other"),
                        ],
                        default="supplier",
                        max_length=20,
                    ),
                ),
                (
                    "risk_tier",
                    models.CharField(
                        choices=[
                            ("tier1", "Tier 1 – Critical"),
                            ("tier2", "Tier 2 – High"),
                            ("tier3", "Tier 3 – Medium"),
                            ("tier4", "Tier 4 – Low"),
                        ],
                        default="tier3",
                        max_length=10,
                    ),
                ),
                ("website", models.URLField(blank=True)),
                ("contact_name", models.CharField(blank=True, max_length=150)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=30)),
                ("contract_start", models.DateField(blank=True, null=True)),
                ("contract_end", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True)),
                ("services_provided", models.TextField(blank=True)),
                ("data_shared", models.BooleanField(default=False)),
                ("processing_personal_data", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_vendors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Third Party",
                "verbose_name_plural": "Third Parties",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ThirdPartyReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("review_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("overdue", "Overdue"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                (
                    "risk_rating",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("tier1", "Tier 1 – Critical"),
                            ("tier2", "Tier 2 – High"),
                            ("tier3", "Tier 3 – Medium"),
                            ("tier4", "Tier 4 – Low"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("findings", models.TextField(blank=True)),
                ("recommendations", models.TextField(blank=True)),
                ("next_review_date", models.DateField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vendor_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "third_party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="third_parties.thirdparty",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-review_date"],
            },
        ),
    ]
