# Generated by Django 5.0.6 on 2026-04-19 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("third_parties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="thirdparty",
            name="dpa_document_url",
            field=models.URLField(
                blank=True,
                help_text="Link to the signed DPA document",
                verbose_name="DPA Document URL",
            ),
        ),
        migrations.AddField(
            model_name="thirdparty",
            name="dpa_expiry_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="DPA Expiry Date"
            ),
        ),
        migrations.AddField(
            model_name="thirdparty",
            name="dpa_required",
            field=models.BooleanField(
                default=False,
                help_text="Is a Data Processing Agreement required with this party?",
                verbose_name="DPA Required",
            ),
        ),
        migrations.AddField(
            model_name="thirdparty",
            name="dpa_signed_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="DPA Signed Date"
            ),
        ),
    ]
