# Generated by Django 5.0.6 on 2026-04-20 00:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0003_grc_p2_gaps"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("controls", "0003_grc_p2_gaps"),
        ("core", "0006_review_sequence_repr"),
        ("incidents", "0002_grc_p1_gaps"),
        ("risks", "0003_risk_threats_vulnerabilities"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CorrectiveActionPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_object_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("root_cause", models.TextField(blank=True)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("blocked", "Blocked"),
                            ("resolved", "Resolved — Pending Verification"),
                            ("verified", "Verified Closed"),
                            ("overdue", "Overdue"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                    ),
                ),
                ("target_completion_date", models.DateField(blank=True, null=True)),
                ("actual_completion_date", models.DateField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("verification_notes", models.TextField(blank=True)),
                ("progress_pct", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Corrective Action Plan",
                "verbose_name_plural": "Corrective Action Plans",
                "ordering": ["target_completion_date", "-created_at"],
            },
        ),
        migrations.RenameIndex(
            model_name="review",
            new_name="core_review_content_6b11b1_idx",
            old_name="core_review_ct_obj_idx",
        ),
        migrations.AddField(
            model_name="automatedaction",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="automatedaction",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="automatedaction",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="approver",
            field=models.ForeignKey(
                blank=True,
                help_text="Checker — person approving the review",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviews_approved",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="evidence",
            field=models.TextField(
                blank=True, help_text="Evidence references or links"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="reviewer",
            field=models.ForeignKey(
                help_text="Maker — person conducting the review",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reviews_conducted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="statusrule",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="statusrule",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="correctiveactionplan",
            name="compliance_requirement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="corrective_actions",
                to="compliance.requirement",
            ),
        ),
        migrations.AddField(
            model_name="correctiveactionplan",
            name="control",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="corrective_actions",
                to="controls.control",
            ),
        ),
        migrations.AddField(
            model_name="correctiveactionplan",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="correctiveactionplan",
            name="incident",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="corrective_actions",
                to="incidents.incident",
            ),
        ),
        migrations.AddField(
            model_name="correctiveactionplan",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="corrective_actions_owned",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="correctiveactionplan",
            name="risk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="corrective_actions",
                to="risks.risk",
            ),
        ),
        migrations.AddField(
            model_name="correctiveactionplan",
            name="source_content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="corrective_action_sources",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="correctiveactionplan",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="correctiveactionplan",
            name="verifier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="corrective_actions_verified",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="correctiveactionplan",
            index=models.Index(
                fields=["source_content_type", "source_object_id"],
                name="core_correc_source__869e46_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="correctiveactionplan",
            index=models.Index(
                fields=["status", "target_completion_date"],
                name="core_correc_status_e0397c_idx",
            ),
        ),
    ]
