apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mira-media-pvc
  namespace: mira
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mira-redis-pvc
  namespace: mira
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard
