# Generated by Django 5.0.6 on 2026-04-20 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="goal",
            name="iso27001_clause",
            field=models.CharField(
                blank=True,
                help_text="e.g. '6.2 Information security objectives', '9.1 Monitoring'",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="goal",
            name="measurable_target",
            field=models.CharField(
                blank=True,
                help_text="Human-readable target, e.g. '99.9% uptime', '<2 critical vulnerabilities'",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="goal",
            name="objective",
            field=models.TextField(
                blank=True,
                help_text="Specific outcome expected when this goal is achieved.",
            ),
        ),
        migrations.AlterField(
            model_name="goal",
            name="unit",
            field=models.CharField(
                blank=True,
                help_text="Unit of measure, e.g. %, count, hours, days",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="goalauditschedule",
            name="audit_criteria",
            field=models.TextField(
                blank=True, help_text="Standards and criteria for the audit"
            ),
        ),
        migrations.AlterField(
            model_name="goalreview",
            name="actions_required",
            field=models.TextField(blank=True, help_text="Specific corrective actions"),
        ),
        migrations.AlterField(
            model_name="goalreview",
            name="approver",
            field=models.ForeignKey(
                blank=True,
                help_text="Checker — person approving the review",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="goal_reviews_approved",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="goalreview",
            name="current_value",
            field=models.FloatField(
                blank=True, help_text="Measured value at time of review", null=True
            ),
        ),
        migrations.AlterField(
            model_name="goalreview",
            name="findings",
            field=models.TextField(blank=True, help_text="Observations and evidence"),
        ),
        migrations.AlterField(
            model_name="goalreview",
            name="reviewer",
            field=models.ForeignKey(
                help_text="Maker — person conducting the review",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="goal_reviews_made",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
