# Generated by Django 5.0.6 on 2026-03-18 15:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("third_parties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSubjectRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("access", "Right of Access"),
                            ("erasure", "Right to Erasure"),
                            ("portability", "Right to Data Portability"),
                            ("rectification", "Right to Rectification"),
                            ("restriction", "Right to Restriction"),
                            ("objection", "Right to Object"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("verified", "Identity Verified"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("denied", "Denied"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="received",
                        max_length=15,
                    ),
                ),
                ("data_subject_name", models.CharField(max_length=200)),
                ("data_subject_email", models.EmailField(max_length=254)),
                ("description", models.TextField()),
                ("received_at", models.DateTimeField()),
                ("deadline", models.DateField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("response_notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "handler",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dsr_handled",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Subject Request",
                "ordering": ["deadline"],
            },
        ),
        migrations.CreateModel(
            name="ProcessingActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("controller", models.CharField(blank=True, max_length=255)),
                ("processor", models.CharField(blank=True, max_length=255)),
                ("purpose", models.TextField()),
                (
                    "legal_basis",
                    models.CharField(
                        choices=[
                            ("consent", "Consent"),
                            ("contract", "Contract"),
                            ("legal_obligation", "Legal Obligation"),
                            ("vital_interests", "Vital Interests"),
                            ("public_task", "Public Task"),
                            ("legitimate_interests", "Legitimate Interests"),
                        ],
                        max_length=30,
                    ),
                ),
                ("data_subjects", models.TextField()),
                ("personal_data_categories", models.TextField()),
                ("special_category_data", models.BooleanField(default=False)),
                ("retention_period", models.CharField(blank=True, max_length=100)),
                ("cross_border_transfer", models.BooleanField(default=False)),
                ("transfer_safeguards", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processing_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "third_party_recipients",
                    models.ManyToManyField(
                        blank=True,
                        related_name="processing_activities",
                        to="third_parties.thirdparty",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Processing Activity",
                "verbose_name_plural": "Processing Activities",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DPIA",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_review", "In Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=15,
                    ),
                ),
                ("necessity_assessment", models.TextField(blank=True)),
                ("proportionality_assessment", models.TextField(blank=True)),
                ("risk_description", models.TextField(blank=True)),
                ("mitigation_measures", models.TextField(blank=True)),
                (
                    "residual_risk_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("very_high", "Very High"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("dpo_consultation_required", models.BooleanField(default=False)),
                ("dpo_opinion", models.TextField(blank=True)),
                ("approved_at", models.DateField(blank=True, null=True)),
                ("review_date", models.DateField(blank=True, null=True)),
                (
                    "assessor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dpias",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "processing_activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dpias",
                        to="privacy.processingactivity",
                    ),
                ),
            ],
            options={
                "verbose_name": "DPIA",
                "verbose_name_plural": "DPIAs",
                "ordering": ["-created_at"],
            },
        ),
    ]
