# Generated by Django 5.0.6 on 2026-04-14 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("privacy", "0001_initial"),
        ("risks", "0003_risk_threats_vulnerabilities"),
    ]

    operations = [
        migrations.AddField(
            model_name="dpia",
            name="privacy_risks",
            field=models.ManyToManyField(
                blank=True,
                related_name="dpias",
                to="risks.risk",
                verbose_name="Privacy Risks",
            ),
        ),
    ]
