# Generated by Django 5.0.6 on 2026-04-19 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("privacy", "0002_dpia_privacy_risks_m2m"),
    ]

    operations = [
        migrations.AddField(
            model_name="processingactivity",
            name="security_measures",
            field=models.TextField(
                blank=True,
                help_text="Art. 30(1)(g) – describe the TOM applied to this processing activity",
                verbose_name="Technical & Organisational Security Measures",
            ),
        ),
    ]
