# Generated by Django 5.0.6 on 2026-04-20 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("privacy", "0003_grc_p1_gaps"),
    ]

    operations = [
        migrations.AddField(
            model_name="dpia",
            name="dpo_consulted_date",
            field=models.DateField(
                blank=True,
                help_text="Art. 36 – date the DPO was formally consulted",
                null=True,
                verbose_name="DPO Consultation Date",
            ),
        ),
    ]
