# Generated by Django 5.0.6 on 2026-04-20 00:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("privacy", "0004_grc_p2_gaps"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsentRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "data_subject_identifier",
                    models.CharField(
                        db_index=True,
                        help_text="Email, customer ID, or other stable subject identifier.",
                        max_length=255,
                    ),
                ),
                ("data_subject_name", models.CharField(blank=True, max_length=200)),
                (
                    "purpose",
                    models.CharField(
                        help_text="Specific, explicit purpose for which consent is given.",
                        max_length=255,
                    ),
                ),
                (
                    "legal_basis_text",
                    models.TextField(
                        blank=True,
                        help_text="The wording the data subject saw at consent time (Art. 7(2) clarity).",
                    ),
                ),
                (
                    "consent_version",
                    models.CharField(
                        blank=True,
                        help_text="Version of the consent notice / privacy notice presented.",
                        max_length=50,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("web_form", "Web Form"),
                            ("email", "Email"),
                            ("in_person", "In Person"),
                            ("paper", "Paper / Signed Form"),
                            ("api", "API / Programmatic"),
                            ("phone", "Phone"),
                            ("other", "Other"),
                        ],
                        default="web_form",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("granted", "Granted"),
                            ("withdrawn", "Withdrawn"),
                            ("expired", "Expired"),
                            ("pending", "Pending"),
                        ],
                        db_index=True,
                        default="granted",
                        max_length=15,
                    ),
                ),
                ("granted_at", models.DateTimeField(blank=True, null=True)),
                ("withdrawn_at", models.DateTimeField(blank=True, null=True)),
                ("withdrawal_reason", models.TextField(blank=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                (
                    "evidence_ref",
                    models.CharField(
                        blank=True,
                        help_text="Reference to signed document, log entry, or screenshot.",
                        max_length=255,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "processing_activity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consents",
                        to="privacy.processingactivity",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Consent Record",
                "verbose_name_plural": "Consent Records",
                "ordering": ["-granted_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConsentEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("granted", "Granted"),
                            ("withdrawn", "Withdrawn"),
                            ("renewed", "Renewed"),
                            ("expired", "Expired"),
                            ("updated", "Updated"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "actor",
                    models.CharField(
                        blank=True,
                        help_text="Who performed the action (subject email, admin user, system).",
                        max_length=255,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "consent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="privacy.consentrecord",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consent Event",
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.AddIndex(
            model_name="consentrecord",
            index=models.Index(
                fields=["data_subject_identifier", "status"],
                name="privacy_con_data_su_a1d616_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="consentrecord",
            index=models.Index(
                fields=["processing_activity", "status"],
                name="privacy_con_process_b0666e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="consentevent",
            index=models.Index(
                fields=["consent", "event_type"], name="privacy_con_consent_fde488_idx"
            ),
        ),
    ]
