# Generated by Django 5.0.6 on 2026-04-19 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="breach_notification_deadline",
            field=models.DateTimeField(
                blank=True,
                help_text="Art. 33 – auto-set to detected_at + 72 h when is_data_breach is True",
                null=True,
                verbose_name="72-hour SA Notification Deadline",
            ),
        ),
    ]
