# Generated by Django 5.0.6 on 2026-04-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0002_grc_p1_gaps"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="notified_authorities_at",
            field=models.DateTimeField(
                blank=True,
                help_text="GDPR Art. 33 – supervisory authority notification timestamp",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="notified_subjects_at",
            field=models.DateTimeField(
                blank=True,
                help_text="GDPR Art. 34 – data subject notification timestamp",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="incidentupdate",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("detection", "Detection"),
                    ("triage", "Triage"),
                    ("containment", "Containment"),
                    ("eradication", "Eradication"),
                    ("recovery", "Recovery"),
                    ("communication", "Communication"),
                    ("notification", "Regulatory Notification"),
                    ("lessons", "Lessons Learned"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
