# Generated by Django 5.0.6 on 2026-03-18 15:26

import apps.accounts.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.accounts.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="business_units",
            field=models.ManyToManyField(
                blank=True,
                related_name="members",
                to="organizations.businessunit",
                verbose_name="Business Units",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user can log into this admin site.",
                verbose_name="staff status",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has all permissions without explicitly assigning them.",
                verbose_name="superuser status",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrator"),
                    ("risk_manager", "Risk Manager"),
                    ("risk_reviewer", "Risk Reviewer"),
                    ("asset_reviewer", "Asset Reviewer"),
                    ("compliance_analyst", "Compliance Analyst"),
                    ("auditor", "Auditor"),
                    ("audit_owner", "Audit Owner"),
                    ("control_owner", "Control Owner"),
                    ("evidence_owner", "Evidence Owner"),
                    ("policy_owner", "Policy Owner"),
                    ("policy_approver", "Policy Approver"),
                    ("viewer", "Viewer"),
                ],
                db_index=True,
                default="viewer",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AlterField(
            model_name="userinvitation",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrator"),
                    ("risk_manager", "Risk Manager"),
                    ("risk_reviewer", "Risk Reviewer"),
                    ("asset_reviewer", "Asset Reviewer"),
                    ("compliance_analyst", "Compliance Analyst"),
                    ("auditor", "Auditor"),
                    ("audit_owner", "Audit Owner"),
                    ("control_owner", "Control Owner"),
                    ("evidence_owner", "Evidence Owner"),
                    ("policy_owner", "Policy Owner"),
                    ("policy_approver", "Policy Approver"),
                    ("viewer", "Viewer"),
                ],
                default="viewer",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="UserGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "default_role",
                    models.CharField(
                        choices=[
                            ("admin", "Administrator"),
                            ("risk_manager", "Risk Manager"),
                            ("risk_reviewer", "Risk Reviewer"),
                            ("asset_reviewer", "Asset Reviewer"),
                            ("compliance_analyst", "Compliance Analyst"),
                            ("auditor", "Auditor"),
                            ("audit_owner", "Audit Owner"),
                            ("control_owner", "Control Owner"),
                            ("evidence_owner", "Evidence Owner"),
                            ("policy_owner", "Policy Owner"),
                            ("policy_approver", "Policy Approver"),
                            ("viewer", "Viewer"),
                        ],
                        default="viewer",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business_units",
                    models.ManyToManyField(
                        blank=True,
                        related_name="user_groups",
                        to="organizations.businessunit",
                        verbose_name="Business Units",
                    ),
                ),
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_group_profile",
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Group",
                "verbose_name_plural": "User Groups",
                "ordering": ["group__name"],
            },
        ),
    ]
