# Generated by Django 5.0.6 on 2026-04-20 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controls", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="controltest",
            name="evidence_file",
            field=models.FileField(
                blank=True,
                help_text="Upload a supporting evidence document for this test",
                null=True,
                upload_to="control_evidence/%Y/%m/",
                verbose_name="Evidence File",
            ),
        ),
    ]
