# Generated by Django 5.0.6 on 2026-04-10 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("risks", "0002_risk_residual_description"),
        ("threats", "0003_risk_threats_vulnerabilities"),
    ]

    operations = [
        migrations.AddField(
            model_name="risk",
            name="threats",
            field=models.ManyToManyField(
                blank=True, related_name="risks", to="threats.threat"
            ),
        ),
        migrations.AddField(
            model_name="risk",
            name="vulnerabilities",
            field=models.ManyToManyField(
                blank=True, related_name="risks", to="threats.vulnerability"
            ),
        ),
    ]
