# Generated by Django 5.0.6 on 2026-03-18 15:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessImpactAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rto_hours",
                    models.PositiveIntegerField(
                        default=24, help_text="Recovery Time Objective in hours"
                    ),
                ),
                (
                    "rpo_hours",
                    models.PositiveIntegerField(
                        default=4, help_text="Recovery Point Objective in hours"
                    ),
                ),
                (
                    "mtpd_hours",
                    models.PositiveIntegerField(
                        default=72,
                        help_text="Maximum Tolerable Period of Disruption in hours",
                    ),
                ),
                (
                    "financial_impact_per_hour",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "reputational_impact",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("dependencies", models.TextField(blank=True)),
                ("minimum_resources", models.TextField(blank=True)),
                (
                    "business_process",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bia",
                        to="organizations.businessprocess",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Business Impact Analysis",
                "verbose_name_plural": "Business Impact Analyses",
            },
        ),
        migrations.CreateModel(
            name="ContinuityPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("scope", models.TextField()),
                ("objectives", models.TextField()),
                ("triggers", models.TextField()),
                ("procedures", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("approved", "Approved"),
                            ("retired", "Retired"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("version", models.CharField(default="1.0", max_length=20)),
                ("approved_at", models.DateField(blank=True, null=True)),
                ("review_date", models.DateField(blank=True, null=True)),
                (
                    "business_processes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="continuity_plans",
                        to="organizations.businessprocess",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="continuity_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Continuity Plan",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="ContinuityTest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "test_type",
                    models.CharField(
                        choices=[
                            ("tabletop", "Tabletop Exercise"),
                            ("simulation", "Simulation"),
                            ("full_activation", "Full Activation"),
                            ("walkthrough", "Walkthrough"),
                        ],
                        max_length=20,
                    ),
                ),
                ("test_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=15,
                    ),
                ),
                ("objectives", models.TextField()),
                ("result_summary", models.TextField(blank=True)),
                (
                    "rto_achieved_hours",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("issues_found", models.TextField(blank=True)),
                ("lessons_learned", models.TextField(blank=True)),
                ("next_test_date", models.DateField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead_tester",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="continuity_tests_led",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tests",
                        to="continuity.continuityplan",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Continuity Test",
                "ordering": ["-test_date"],
            },
        ),
    ]
