apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mira.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mira.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.backend.secretKey | quote }}
  EMAIL_HOST_USER: {{ .Values.email.user | quote }}
  EMAIL_HOST_PASSWORD: {{ .Values.email.password | quote }}
  {{- if .Values.oidc.enabled }}
  OIDC_CLIENT_ID: {{ .Values.oidc.clientId | quote }}
  OIDC_CLIENT_SECRET: {{ .Values.oidc.clientSecret | quote }}
  {{- end }}
