# Generated by Django 5.0.6 on 2026-04-12 21:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_add_scope_org_issue"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="scope",
            name="approver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scope_checker_docs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Checker (Approver)",
            ),
        ),
        migrations.AlterField(
            model_name="scope",
            name="next_review_date",
            field=models.DateField(
                blank=True,
                help_text="Auto-computed on approval; must be set for every review cycle",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="scope",
            name="review_periodicity_days",
            field=models.PositiveIntegerField(
                choices=[
                    (30, "Monthly (30 days)"),
                    (60, "Bi-Monthly (60 days)"),
                    (90, "Quarterly (90 days)"),
                    (180, "Semi-Annual (180 days)"),
                    (365, "Annual (365 days)"),
                    (730, "Bi-Annual (730 days)"),
                ],
                default=365,
                help_text="How many days between reviews (mandatory)",
            ),
        ),
        migrations.AlterField(
            model_name="scope",
            name="reviewer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scope_maker_docs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Maker (Reviewer)",
            ),
        ),
        migrations.CreateModel(
            name="RiskOpportunity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "item_type",
                    models.CharField(
                        choices=[("risk", "Risk"), ("opportunity", "Opportunity")],
                        db_index=True,
                        default="risk",
                        max_length=20,
                    ),
                ),
                (
                    "likelihood",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1 – Rare"),
                            (2, "2 – Unlikely"),
                            (3, "3 – Possible"),
                            (4, "4 – Likely"),
                            (5, "5 – Almost Certain"),
                        ],
                        default=3,
                    ),
                ),
                (
                    "impact",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1 – Negligible"),
                            (2, "2 – Minor"),
                            (3, "3 – Moderate"),
                            (4, "4 – Major"),
                            (5, "5 – Catastrophic"),
                        ],
                        default=3,
                    ),
                ),
                (
                    "treatment",
                    models.CharField(
                        choices=[
                            ("accept", "Accept"),
                            ("mitigate", "Mitigate"),
                            ("transfer", "Transfer"),
                            ("avoid", "Avoid"),
                            ("exploit", "Exploit (Opportunity)"),
                            ("share", "Share (Opportunity)"),
                            ("enhance", "Enhance (Opportunity)"),
                        ],
                        db_index=True,
                        default="mitigate",
                        max_length=20,
                    ),
                ),
                (
                    "treatment_plan",
                    models.TextField(
                        blank=True, help_text="Actions to address this risk/opportunity"
                    ),
                ),
                (
                    "residual_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Residual Level after Treatment",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_treatment", "In Treatment"),
                            ("monitored", "Monitored"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "linked_issue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="risk_opportunities",
                        to="organizations.organizationalissue",
                        verbose_name="Source Issue (§4.1/§4.2)",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_risk_opportunities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Risk / Opportunity",
                "verbose_name_plural": "Risks & Opportunities",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScopeApprovalHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=20)),
                ("approved_at", models.DateTimeField(auto_now_add=True)),
                ("next_review_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scope_approval_history",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved By",
                    ),
                ),
                (
                    "scope",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_history",
                        to="organizations.scope",
                        verbose_name="Scope",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scope Approval Record",
                "verbose_name_plural": "Scope Approval Records",
                "ordering": ["-approved_at"],
            },
        ),
    ]
