# Generated by Django 5.0.6 on 2026-04-20 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0002_requirementmapping"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="requirementmapping",
            name="unique_requirement_mapping",
        ),
        migrations.AddField(
            model_name="complianceassessment",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Person responsible for meeting this requirement",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_compliance_assessments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="requirementmapping",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="requirementmapping",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="requirementmapping",
            unique_together={("source", "target")},
        ),
    ]
