# Generated by Django 5.0.6 on 2026-04-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0003_grc_p2_gaps"),
    ]

    operations = [
        migrations.AddField(
            model_name="evidence",
            name="valid_until",
            field=models.DateField(
                blank=True,
                help_text="Evidence freshness — auditor-usable until this date.",
                null=True,
            ),
        ),
    ]
