# Generated by Django 5.0.6 on 2026-04-10 05:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("threats", "0002_seed_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="threat",
            name="asset_types",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Asset types this threat applies to, e.g. ['server', 'endpoint', 'cloud']",
            ),
        ),
        migrations.AlterField(
            model_name="threat",
            name="likelihood",
            field=models.PositiveSmallIntegerField(
                default=3,
                help_text="1 (Rare) to 5 (Almost Certain)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="threat",
            name="mitre_attack_id",
            field=models.CharField(
                blank=True,
                help_text="MITRE ATT&CK technique ID, e.g. T1566",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="threat",
            name="severity",
            field=models.PositiveSmallIntegerField(
                default=3,
                help_text="1 (Negligible) to 5 (Critical)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="vulnerability",
            name="asset_types",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Asset types affected by this vulnerability",
            ),
        ),
        migrations.AlterField(
            model_name="vulnerability",
            name="cve_id",
            field=models.CharField(
                blank=True, help_text="CVE identifier if applicable", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="vulnerability",
            name="cvss_score",
            field=models.FloatField(
                blank=True, help_text="CVSS v3 base score (0.0–10.0)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="vulnerability",
            name="remediation",
            field=models.TextField(
                blank=True, help_text="Recommended remediation steps"
            ),
        ),
        migrations.AlterField(
            model_name="vulnerability",
            name="severity",
            field=models.PositiveSmallIntegerField(
                default=3,
                help_text="1 (Low) to 5 (Critical)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
